### ISSUE TITLE
.gitignore dosyası olsa güzel olurdu

### ISSUE THREAD

**Issue by mactorient** [ubselcuk/bai-bai#69]

**Comment by Dines97** [comment]
Oda git egitmlerin bir parcasi olarak dusenebilirsiniz. Hemde bizim .gitignore dosyasi eklememize gerek yok. Sizin KENDI KLASORUNUZE icine eklerseniz o ve onun altindaki butun klasorlerde etkili olur. Boylece basklarin da kendi .gitignore lari yazma sanslari olur. Bunu gorevlere ekleyebilirim ama son zamanlarda mesgulum.
